---
title: 14 期约与异步函数
top: 14
tags:
  - JavaScript
categories:
  - JavaScript
---

### 期约

期约是对尚不存在的结果的一个替身。ES6新增的应用类型 Promise，可以通过 new 操作符来实例化。

期约是一个有状态的对象，有三种状态：

* 待定（pending）
* 兑换（fulfilled，有时也称为“解决”，resolved）
* 拒绝（rejected）

待定（pending）是期约最初始状态。在待定状态，期约可以落定（settled）为代表成果的兑换（fulfilled）状态，或者代表失败的拒绝（rejected）状态。无论螺钉为那种状态都是不可逆的。

期约的状态是私有的，不能直接通过 JavaScript 检测到，只能在内部进行操作。内部操作在

期约的执行器函数中完成。执行器函数主要有两项职责：初始化期约的异步行为和控制状态的转换。这两个函数参数通常命名为 resolve() 和 reject() 。调用resolve()会把状态切换为兑换，调用 reject() 会被状态切换为拒绝，且会抛出错误，但不会影响后续代码的执行。resolve()方法可传递data数据，而reject()方法可传递err错误。

```javascript
let p1 = new Promise((resolve, reject) => resolve());
console.log(p1); // Promise { <state>: "fulfilled", <value>: undefined }
let p2 = new Promise((resolve, reject) => reject()); // Uncaught (in promise)
console.log(p2); // Promise { <state>: "rejected", <reason>: undefined }
```

Promise 本身不是异步，但却是用来封装异步任务的。

Promise 参数的函数体中的代码会在 new Promise 时以异步方式立即执行：

```javascript
let p1 = new Promise((resove, reject) => {
    setTimeout(() => { console.log(1) }, 100)
    resove();
})

let p2 = new Promise((resove, reject) => {
    setTimeout(() => { console.log(2) }, 100);
    resove();
})

let p3 = new Promise((resove, reject) => {
    console.log("3");
    resove();
})
// 1 3 1
```

#### 链式调用

then 可用于实现 Promise 的链式调用。注意。是针对 Promise 的结果进行链式调用。

返回结果如果是 Promise 对象，对象状态由回调函数的执行结果来决定。
如果回调函数中 return 的是非 Promise 类型时，状态为成功。

```javascript
let p1 = new Promise((resove, reject) => {
    console.log("p1执行完成");
    resove("1")
})

let p2 = new Promise((resove, reject) => {
    setTimeout(() => {
        console.log("p2执行完成");
        resove("2");
    }, 10)

})

let p3 = new Promise((resove, reject) => {
    console.log("p3执行完成");
    resove("3")
})

p1
    .then((data) => {
    console.log(data);
    return p2;
}, (err) => {
    console.log(err);
})
    .then((data) => {
    console.log(data);
    return p3;
})
    .then((data) => {
    console.log(data);
})
```

#### Promise.all()

Promise.all() 方法接收一个 promise 的 iterable 类型（注：Array，Map，Set 都属于 ES6 的 iterable 类型）的输入，并且只返回一个 Promise 实例。只要任何一个输入的 promise 的 reject 回调执行或者输入不合法的 promise 就会立即抛出错误，并且 reject 的是第一个抛出的错误信息。

```javascript
const p1 = Promise.reject(1);
const p2 = Promise.reject(2);
Promise.all([p1, p2])
    .then(values => {
    console.log('resolve: ', values)
}).catch(err => {
    console.log('reject: ', err)
})
// reject:  1
```

#### Promise.allSettled()

该方法参数与Promise.all() 方法相同，Promise.allSettled()方法返回一个在所有给定的 promise 都已经`fulfilled`或`rejected`后的 promise，并带有一个对象数组，每个对象表示对应的 promise 结果。

```javascript
const p1 = Promise.resolve(1);
const p2 = new Promise((resolve, reject) => setTimeout(reject, 100));
const p3 = Promise.reject();
Promise.allSettled([p1, p2, p3]).
then((results) => results.forEach((result) => console.log(result.status)));
// fulfilled rejected rejected
```

#### Promise.race()

该方法参数与 Promise.all() 方法相同，Promise.all() 方法的返回值将采用第一个 promise 的值作为它的值。

```javascript
const p = Promise.race([
    //  该 Promise 在 1s 后才成功，而后一个在 0.5s 后就拒绝了，所以最快的为第二个。
    // 注意，即使已将最快的 Promise 执行完，但其他的所有 异步任务仍会执行
    new Promise((resolve, reject) => {
        setTimeout(() => resolve, 1000)
    }),
    new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error('timeout'), 500)
    })
]);
p.catch(error => console.log(error));
```

### 异步函数

ES8新增了两个关键字：async 和 await。

async 关键字用于声明异步函数，可以让函数具有异步特征，但总体上其代码仍然是同步求值的。异步函数如果使用 return 关键字返回了值，这个值会被 Promise.resolve() 包装成一个期约对象。

await关键字会暂停执行异步函数后的代码，尝试”解包“对象的值。

await 的 promise 失败了，就会抛出异常需要通过 try…catch 来捕获